spring:
  application:
    name: devs4j-dragon-ball
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"