spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raidentrance/devs4j-config
          default-label: main
          clone-on-start: true
          
server:
  port: 8888